name: Deployment

on:
  push:
    branches: [master]


jobs:
  deployment:
    runs-on: ubuntu-latest
    steps: 
      - name: Upload to Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ../
          server-dir: /sites/floaty.alexishadjian.com/